services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    ports:
      - "3000:3000"
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./
  #     dockerfile: ./frontend/Dockerfile
  #   ports:
  #     - "80:80"
  # storybook:
  #   container_name: storybook
  #   build:
  #     context: ./
  #     dockerfile: ./frontend/DockerfileStoryBook
  #   ports:
  #     - "6006:6006"
